import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"] });

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Tina's Treehouse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
